const data = {
  products: [
    {
      name: 'Red Bull Racing hoodie',
      slug: 'redbull-racing-hoodie',
      category: 'hoodie',
      image: '/images/redbull-hoodie.png',
      price: 69.99,
      CountInStock: 11,
      brand: 'Red Bull Racing',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality hoodie',
    },
    {
      name: 'Ferrari Classic T-shirt',
      slug: 'ferrari-classic-tshirt',
      category: 'T-shirts',
      image: '/images/ferrari-tshirt.png',
      price: 39.99,
      countInStock: 20,
      brand: 'Scuderia Ferrari',
      rating: 3.4,
      numReviews: 15,
      description: 'Classic red T-shirt with iconic Ferrari logo.',
    },
    {
      name: 'Red Bull Racing jacket',
      slug: 'redbull-racing-jacket',
      category: 'jacket',
      image: '/images/redbull-jacket.png',
      price: 104.99,
      countInStock: 12,
      brand: 'Red Bull Racing',
      rating: 4.7,
      numReviews: 12,
      description: 'jacket with Red Bull Racing team colors and logo.',
    },
    {
      name: 'McLaren Performance hoodie',
      slug: 'mclaren-performance-hoodie',
      category: 'hoodie',
      image: '/images/mclaren-hoodie.png',
      price: 49.99,
      countInStock: 18,
      brand: 'McLaren',
      rating: 4.6,
      numReviews: 10,
      description: 'Performance hoodie with McLaren branding and technology.',
    },
  ],
};
export default data;
